
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import { ContextProvider } from "./context/Favourites";
import { ToastContainer } from "react-toastify";
import {ClerkProvider} from '@clerk/nextjs'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <ContextProvider>
        <body className="bg-gray-200">
          <Header />
          {children}
          <Footer/>
          <ToastContainer toastClassName="toast-position" autoClose={2000}/>
          </body>
      </ContextProvider>
    </html>
    </ClerkProvider>
  );
}
